name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Linux Build
      id: linux
      uses: addnab/docker-run-action@v3
      with:
        image: debian:buster-slim
        options: -v ${{ github.workspace }}/..:/tmp/build/ 
        run: |
          chmod +x /tmp/build/futurerestore/.github/workflows/linux.sh
          /tmp/build/futurerestore/.github/workflows/linux.sh
    - name: Linux Copy
      run: |
        export FUTURERESTORE_VERSION_RELEASE=$(cat /home/runner/work/futurerestore/futurerestore/version.txt | tr -d '\n')
        docker cp $(docker ps -ql):/tmp/build/futurerestore-${FUTURERESTORE_VERSION_RELEASE}-linux.tar.xz /home/runner/work/futurerestore/futurerestore/.github/workflows/
    - name: Archive
      id: archive
      uses: actions/upload-artifact@v2
      with:
        name: futurerestore-linux
        path: |
          /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-*.tar.xz
